package frontend.Lexer;

public enum TypeCode {
    TYPE_UNDEFINED, TYPE_EOF,
    IDENFR, INTCON, STRCON,
    MAINTK, CONSTTK, INTTK, VOIDTK,
    BREAKTK, CONTINUETK, IFTK, ELSETK,
    WHILETK, GETINTTK, PRINTFTK, RETURNTK,
    NOT, AND, OR,
    PLUS, MINU, MULT, DIV, MOD, BITAND,
    LSS, LEQ, GRE, GEQ, EQL, NEQ,
    ASSIGN, SEMICN, COMMA,
    LPARENT, RPARENT, LBRACK, RBRACK, LBRACE, RBRACE
}
